Import("env")
import re
import os

def generate_prototypes(*args, **kwargs):
    """
    Generate function prototypes from all .ino files
    This mimics what Arduino IDE does automatically
    """
    src_dir = os.path.join(env.get("PROJECT_DIR"), "Firmware", "RTK_Everywhere")
    prototypes_h = os.path.join(src_dir, "auto_prototypes.h")

    # List of .ino files to scan
    ino_files = []
    for file in os.listdir(src_dir):
        if file.endswith(".ino"):
            ino_files.append(os.path.join(src_dir, file))

    # Patterns to match function declarations
    # Matches: type function_name(params)
    function_pattern = re.compile(
        r'^(?:(?:const|static|inline|virtual)\s+)*'  # Optional modifiers
        r'(?:void|int|bool|char|float|double|uint8_t|uint16_t|uint32_t|int8_t|int16_t|int32_t|int64_t|size_t|'
        r'const\s+char\s*\*|char\s*\*|void\s*\*|[A-Z][a-zA-Z0-9_]*)\s+'  # Return type
        r'([a-zA-Z_][a-zA-Z0-9_]*)\s*\('  # Function name
        r'[^)]*\)',  # Parameters
        re.MULTILINE
    )

    prototypes = set()

    # Scan all .ino files for function definitions
    for ino_file in ino_files:
        try:
            with open(ino_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()

                # Find all function definitions
                for match in function_pattern.finditer(content):
                    line = match.group(0)
                    # Skip lines that are already in class definitions or comments
                    if not line.strip().startswith('//') and '::' not in line:
                        # Add semicolon if not present
                        if not line.rstrip().endswith(';'):
                            line = line.rstrip() + ';'
                        prototypes.add(line)
        except Exception as e:
            print(f"Warning: Could not parse {ino_file}: {e}")

    # Write prototypes to header file
    with open(prototypes_h, 'w') as f:
        f.write("// Auto-generated function prototypes\n")
        f.write("// This file is generated by scripts/pre_build.py\n")
        f.write("#ifndef AUTO_PROTOTYPES_H\n")
        f.write("#define AUTO_PROTOTYPES_H\n\n")

        for prototype in sorted(prototypes):
            f.write(prototype + '\n')

        f.write("\n#endif // AUTO_PROTOTYPES_H\n")

    print(f"Generated {len(prototypes)} function prototypes in {prototypes_h}")

# Register the callback
env.AddPreAction("buildprog", generate_prototypes)
